

spring:

  # Database
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://localhost:3306/saury?serverTimezone=Asia/Shanghai&characterEncoding=utf-8'

  # JPA
  jpa:
    show-sql: true
    database: 'mysql'
    database-platform: 'org.hibernate.dialect.MySQL8Dialect'
    hibernate:
      ddl-auto: 'update'
      naming:
        # 指定 JPA 的自动表生成策略，驼峰自动映射为下划线格式
        implicit-strategy: 'org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl'

  mvc:
    static-path-pattern: '/static/**'

  web:
    resources:
      static-locations: 'classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:static'

  # Email
  mail:
    host: 'smtp.163.com'
    port: 25
    protocol: 'smtp'
    default-encoding: 'UTF-8'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# Sa-Token 配置
sa-token:
  # token 名称 (同时也是 cookie 名称)
  token-name: Authorization
  # token 有效期，单位秒，-1代表永不过期
  timeout: 2592000
  # token 临时有效期 (指定时间内无操作就视为token过期)，单位秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为 false 时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为 false 时每次登录新建一个 token)
  is-share: false
  # token 风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 是否从 cookie 中读取 token
  is-read-cookie: true